[package]
name = "liczba_slownie"
version = "0.1.0"
authors = ["Maks Rawski <maksymilian.rawski@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
